### ISSUE TITLE
Styling of the homepage 

### ISSUE THREAD

**Issue by mkouba** [smallrye/smallrye.github.io#11]
I like the background image but the text is not very readable... I think we should add some background-color to the hero div, something like:

![Snímek obrazovky_2019-09-04_16-02-16](https://user-images.githubusercontent.com/913004/64262058-cd847a00-cf2d-11e9-9fe0-aa9379c620f8.png)

And apply similar styles to the top right menu and highlights too.

**Comment by kenfinnigan** [comment]
@jkbrock, could you add this to the list to review along with the overall CSS of the site when the team can fit it in the schedule? thanks

**Comment by jkbrock** [comment]
Yes! I'll take a look this weekend.

**Comment by albertotn** [comment]
hi, just checked on Firefox 73.0 and look like this:

![immagine](https://user-images.githubusercontent.com/12526457/74812712-4ae15280-52f4-11ea-9b49-d766db4334c7.png)

**Comment by Maldivia** [comment]
Or perhaps consider add a stroke/text-shadow to the text?
For instance add the following added to `home-hero`:
```
text-shadow: -1px -1px 0 #000, 1px -1px 0 #000, -1px 1px 0 #000, 1px 1px 0 #000;
```
Produces the following before and after:
![image](https://user-images.githubusercontent.com/1133537/89288888-09a0ed00-d65f-11ea-8933-88a001e10806.png)

**Comment by Ladicek** [comment]
The most important thing that needs to happen to the homepage, IMNSHO, is the background image losing weight. It's more than 5 MBs now!

**Comment by radcortez** [comment]
Does anyone have the skills for it? :D
