### ISSUE TITLE
Add CDI, JAX-RS, JSON-P, JSON-B ?

### ISSUE THREAD

**Issue by agoncal** [smallrye/smallrye.github.io#8]
In page https://github.com/smallrye/smallrye.github.io/blob/develop/projects/overview.adoc I think it would be nice to mention the Java EE specifications and versions that Microprofile support (CDI, JAX-RS, JSON-P, JSON-B). Don't you think ?

**Comment by kenfinnigan** [comment]
Not sure as SmallRye doesn't define or provide a full server of any kind that you can take and use, only the pieces specific to MicroProfile.

The Java EE specifications and versions that are part of a MicroProfile server are dependent on where an application is deployed.

Maybe the column header for a spec could link to where all the spec versions are defined, which includes the Java EE specifications and versions?

**Comment by agoncal** [comment]
Well, each time you read about Microprofile (e.g. https://microprofile.io/resources) it mentions CDI + JAX-RS + JSON-P. So I think it would be important to add those specs to the table (for example, Microprofile does not support JMS, nor Smallrye). I find it would add more value/information to the new comer, this way (s)he knows you can use CDI in Smallrye.

**Comment by tomqwpl** [comment]
However, I'm now confused, as I'm struggling to find the smallrye implementation of Json-P. I take it from this that there isn't one.

**Comment by radcortez** [comment]
Hi @tomqwpl 

There isn't. SmallRye focus on the specs introduced by MicroProfile. Since CDI, JAX-RS, JSON-P and JSON-B are coming from Jakarta, we don't have implementations for those.

If you want a JSON-P implementation, my recommendation is to look here: https://github.com/eclipse-ee4j/jsonp

**Comment by tomqwpl** [comment]
Yes. My point really was that the change that this issue introduced caused me confusion, and it makes it look like there's an implementation, but just that the links are missing from the table or something.
